### ISSUE TITLE
Missing translation for Data to export options

### ISSUE THREAD

**Issue by manh-nguyen** [Agence-DnD/DnD-MagentoConnectorBundle#17]
Hi Guys,

It's just a minor request.
DnD Magento Connector Bundle export product:
Please translate these options to english
Data to export: 
- tout exporter
- tout exporter sauf les prix
- exporter les prix uniquement

Regards,
Manh

**Comment by DnD-Mimosa** [comment]
Hi Manh,

Here is the translation, it will be implemented in a futur release :
- tout exporter -> Export All Data
- tout exporter sauf les prix -> Export All Data without prices 
- exporter les prix uniquement -> Export prices only

Regards,
Florian
