### ISSUE TITLE
Cant see the connector option

### ISSUE THREAD

**Issue by ghost** [Agence-DnD/DnD-MagentoConnectorBundle#19]
Hi there,
I have installed the connector but when I go to create a new export profile I don't see any DnD options.

**Comment by DnD-Mimosa** [comment]
Hi Adam,

Did you add the following line in your AppKernel.php :
$bundles[] = new DnD\Bundle\MagentoConnectorBundle\DnDMagentoConnectorBundle();

Also, don't forget to clear your PIM cache with the following command line :
app/console cache:clear -e=prod

Regards,
Florian.

**Comment by ghost** [comment]
Thankyou. I had to manually clear the cache and then force a reinstall. But all working now. Thanks
