### ISSUE TITLE
How do we map images

### ISSUE THREAD

**Issue by ghost** [Agence-DnD/DnD-MagentoConnectorBundle#21]
After setting up images in Akeneo. How do we map these in Magento?

**Comment by DnD-Mimosa** [comment]
Hi,

You don't need to map your images in Magento. In fact, when the images are exported on your distant server, you can find them in your remote image folder path which contain as much as subfolder as you have product. 

Each of these folder name is equal to your products SKU and contain one folder per product media.

So, the first image in the PIM will be the first image in Magento (visible in product list).

When your Akeneo PIM product export is complete, you have to execute the product import in Magento and then, the images import which will associate all the images in the folder which name is equal to your product SKU.

I hope that my response helped you.

Regards,
Florian.
