### ISSUE TITLE
Confirmed working combination for Akeneo PIM + DnD-MagentoConnectorBundle?

### ISSUE THREAD

**Issue by juha78** [Agence-DnD/DnD-MagentoConnectorBundle#28]
After trying to install DnD-MagentoConnectorBundle for many days I have to check if someone could confirm working combination. I can get things installed but the exports menu does not appear even if I enable the plugin in AppKernel.php

Does this requirement Akeneo PIM Stable mean Akeneo PIM Community Standard or do I have to have a stable Dev -version ?

Any help finding a working combination of versions would help at this point.

**Comment by amitvkhajanchi** [comment]
I was able to get this to work using akeneo-1.3.9 and Dnd-MagentoConnnectorBundle 1.2.2.  However, the exports translations are not loading properly.  I think there was some compatiblity issues with connector bundle 1.2 with akeneo 1.3 if you read the release notes.

**Comment by DnD-Mimosa** [comment]
Hi @juha78,

Did you clear the Akeneo PIM cache after installing DnD Magento Connector Bundle by executing the following ssh command line :

app/console cache:clear -e=prod

Regards,
Florian.
