### ISSUE TITLE
Locales hardcoded in family processor

### ISSUE THREAD

**Issue by antoineguigan** [Agence-DnD/DnD-MagentoConnectorBundle#30]
Cannot export to locales other than fr_FR and en_US

**Comment by DnD-Mimosa** [comment]
Hi Antoine,

A fix has been pushed yesterday. A new field is now available in family export where you have to fill in the language that you want to have for your families in Magento.

By default, the language is set to en_US.

Regards,
Florian.

**Comment by antoineguigan** [comment]
Thanks !
