### ISSUE TITLE
data to export selector, dropdown options

### ISSUE THREAD

**Issue by mrafulfill** [Agence-DnD/DnD-MagentoConnectorBundle#32]
The list of choices shown on the frontend should be the other way around, simply showing "all / without prices / only prices", currently we are seeing the screenshot below.

![schermafdruk 2015-05-30 11 55 09](https://cloud.githubusercontent.com/assets/4086514/7896704/e6450d1c-06c2-11e5-9646-5c75da318d8b.png)
![schermafdruk 2015-05-30 11 55 27](https://cloud.githubusercontent.com/assets/4086514/7896705/ec85fa92-06c2-11e5-9eb7-df44b17bc99f.png)

**Comment by DrewKolstad** [comment]
@mrafulfill Did you clear the cache after you upgraded the module?

If you didn't, try running the following command on your server
`php app/console cache:clear -e prod`
-or (if you are running in dev mode)-
`php app/console cache:clear`

Those options are internally pointing to translated values located in yaml files in the "Resources/translations/" folder of the project. If you have the connector properly installed, and your production or dev cache cleared, the values should populate correctly.
