### ISSUE TITLE
SFTP not transferring files

### ISSUE THREAD

**Issue by margus** [Agence-DnD/DnD-MagentoConnectorBundle#33]
Hello,

I have tested this as much as I can and see the logs on the remote server side and I cant see any action taken regarding file transfers. I have installed the module into Akeneo, and I can see the export connectors. When I check the SFTP logs, I see that the sftp is connecting and then disconnecting and thats it, no file transfer actions and nothing like that happening, when I tested a simple file upload with the same ftp user, I did see that the logs contained more data.
## SFTP log:

May 25 15:34:13 server-xx internal-sftp[723]: session opened for local user pim-test from [xx.xx.xx.xx]
May 25 15:34:13 server-xx internal-sftp[723]: received client version 3
May 25 15:34:13 server-xx internal-sftp[723]: debug1: read eof
May 25 15:34:13 server-xx internal-sftp[723]: debug1: read eof
May 25 15:34:13 server-xx internal-sftp[723]: session closed for local user pim-test from [xx.xx.xx.xx]

So from there I can see that credentials are all correct.

Any idea what might be the case?

**Comment by ahawks122** [comment]
I have the same issue. Any update OR can someone help?

**Comment by ahawks122** [comment]
I found a solution...

In the export profile there is a "File Path" and a "Remote File path". The export process will first create the file locally and then try to upload the file to the remote location. The default "File Path" contains a place holder (%datetime%) which is replaced with the current date and time, but when the process tries to upload the file it is looking for the exact file name in "File Path". So if you remove the datetime place holder and put in a static file name the file should be uploaded.

I hope this helps.

**Comment by nik736** [comment]
Thanks @ahawks122 ! This helped me a lot :)
