### ISSUE TITLE
Need to generate the akeneo's product file from one server to another server using sftp

### ISSUE THREAD

**Issue by maramkoteswar** [Agence-DnD/DnD-MagentoConnectorBundle#34]
Hi,

I have used DND-Magento Connector to generate the categories,families,products file on the same server (using same sftp details),now i would like to generate the files to another server for that i have provided another sftp details (host,port,username and password) and exported but their is no error and prompted files was generated but i haven't see any generated file over new server.

Please help me on this asap.

Thanks in advance

Regards,
Koteswar Maram

**Comment by DnD-Mimosa** [comment]
Hi @maramkoteswar,

Are you sure that you filled the public IP of your remote server ?

Also, can you try to run this export with the following command :
php app/console akeneo:batch:job your_export_profile_code

Regards,
Florian.
