### ISSUE TITLE
Exporting categories and Excluded root categories doesn't work as expected.

### ISSUE THREAD

**Issue by emishusta** [Agence-DnD/DnD-MagentoConnectorBundle#35]
When we create DnD Magento Connector for exporting categories and use Excluded root categories it excludes root categories with only the first level children(children of 3d, 4d, 5d etc levels are present in exported file). Expected that root category with its all children should be excluded.

**Comment by DnD-Mimosa** [comment]
Hi @emishusta,

We just pushed a fix about categories export. In fact all children of an excluded category are now also excluded.

Regards,
Florian.
