### ISSUE TITLE
Dnd MagentoConnectorBundle error for missing dependency after installation

### ISSUE THREAD

**Issue by emaan-zepcom** [Agence-DnD/DnD-MagentoConnectorBundle#47]
I have installed DnDMagentoConnector now i am getting this error for missing service how to fix this issue.
it seems compatibility issue in latest version of akeneo.
![errordnd](https://cloud.githubusercontent.com/assets/14107589/14383396/4f8f2e14-fdae-11e5-8069-4584797b48bd.PNG)

**Comment by DnD-Mimosa** [comment]
Hi,

This bundle is compatible with Akeneo <1.4.

If you are on >1.3, use this bundle instead :
https://github.com/akeneo-labs/EnhancedConnectorBundle

Regards,
Florian.
