### ISSUE TITLE
after install

### ISSUE THREAD

**Issue by thomasb0123** [Agence-DnD/DnD-MagentoConnectorBundle#49]
i got this error on clean i use last version (1.6)
  The parent definition "pim_base_connector.processor.transformer" defined for definition "dnd_magento_connector.processor.family" does not exist.

![capture](https://cloud.githubusercontent.com/assets/3063380/18262700/5304956c-7404-11e6-9eff-5dd2ac11ff4b.PNG)

**Comment by KirianM** [comment]
Same problem here! Any solution?

**Comment by DnD-Magnum** [comment]
Hi @thomasb0123,
This bundle is not available for Akeneo 1.6, just for the first version of Akeneo. You can use the EnhancedConnectorBundle : https://marketplace.akeneo.com/package/enhanced-connector
