### ISSUE TITLE
Not compatible with Akeneo/pim 1.3

### ISSUE THREAD

**Issue by manh-nguyen** [Agence-DnD/DnD-MagentoConnectorBundle#5]
Hi guys,
I got this problem when trying install this bundle

  Problem 1
    - agencednd/magento-connector-bundle v1.2.0 requires akeneo/pim-community-dev 1.2.*@stable -> no matching package found.

https://github.com/Agence-DnD/DnD-MagentoConnectorBundle/blob/master/composer.json
    "require": {
        "ext-ssh2": "*",
        "akeneo/pim-community-dev": "~1.2@stable"
    },

Regards,
Manh

**Comment by johnny1991** [comment]
Hi,

I have the same problem : 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for agencednd/magento-connector-bundle 1.2 -> satisfiable by agencednd/magento-connector-bundle[v1.2.0].
    - agencednd/magento-connector-bundle v1.2.0 requires akeneo/pim-community-dev 1.2.*@stable -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

I think there is problem with minimum-stability.

Johnny1991

**Comment by ArnaudLigny** [comment]
In your own project composer file, be sure the directive `minimum-stability = "dev"` is set.

**Comment by BitOne** [comment]
Hello guys,

To be compatible with Akeneo 1.3, you will need to change the require to use agencednd/magento-connector-bundle dev-master (instead of 1.2) , as the fix is in master but has not yet been released.

**Comment by johnny1991** [comment]
Ok, Good

Thanks
